### ISSUE TITLE
Week 1 Feedback: Farenheit to Celcius

### ISSUE THREAD

**Issue by cferdinandi** [jonmbodnar/projects-js#1]
https://github.com/jonmbodnar/projects-js/tree/master/week-1/temperature-converter

Nice work here! Two small pieces of feedback:

1. There's no benefit to using `Number()` when you set your value, as the `value` of the input will render the same either way.
2. You *might* want to check that the element you're trying to grab (ex. `document.querySelector("#celcius")`) exists before setting it's value. If for some reason is disappeared from the DOM you'd throw an error (unlikely in this specific app).

I in particular liked your use of event bubbling!

**Comment by jonmbodnar** [comment]
I used the Number() method as a way to get rid of any trailing zeros—to convert numbers like 2.20 to 2.2.  So it was purely for aesthetics because I didn't like the way the trailing zeros looked.

Let me know if you know of a better way of doing that.

**Comment by cferdinandi** [comment]
Gotcha! In that case, sound perfect!
