### ISSUE TITLE
Week 1 Feedback: Toggle Passwords

### ISSUE THREAD

**Issue by cferdinandi** [jonmbodnar/projects-js#2]
https://github.com/jonmbodnar/projects-js/tree/master/week-1/toggle-passwords

This is a great start. The biggest challenge with your current approach is:

1. It's deeply tied to the specific markup structure. You're specifically naming the IDs and elements in the DOM, and would need to rewrite it to use it on other pages with different setups.
2. You're repeating yourself a little out of necessity because of item 1.

The trick to abstracting this is to pass in the selector(s) for the elements you want toggle visibility for as part of the checkbox markup. One way to do this is by adding a data attribute (which you can also use as a selector in the event callback).

Here's how I set mine up: https://gist.github.com/cferdinandi/a17979626cb99632ef3deca3a2213948

**Comment by jonmbodnar** [comment]
Thanks for the feedback. It's really useful. I appreciate your taking the time to give it.
